import { Request, Response } from "express";
import { TenantApiServices } from "../services/TenantApiServices";
import { sendErrorResponse, sendSuccessResponse, Errors, ApiError } from "../../../utils/errorHandler";
import type { AuthenticatedRequest } from "../middlewares/auth";

export async function createWebhook(req: Request, res: Response) {
    try {
        const { url, events } = req.body as {
            url?: string;
            events?: string[];
        };

        if (!url) {
            return sendErrorResponse(res, Errors.missingRequired("url"));
        }

        const authReq = req as AuthenticatedRequest;
        const tenantId = authReq.tenant?.id;

        if (!tenantId) {
            return sendErrorResponse(res, Errors.authRequired());
        }

        const tenantApiServices = new TenantApiServices();
        const webhook = await tenantApiServices.createWebhook({
            tenant_id: tenantId,
            url,
            events: events || [],
            secret: "", // Generated by service
        });

        return sendSuccessResponse(res, 201, "Webhook created successfully", {
            id: webhook.id,
            tenant_id: webhook.tenant_id,
            url: webhook.url,
            events: webhook.events,
            created_at: webhook.created_at,
            updated_at: webhook.updated_at,
        });
    } catch (error: any) {
        if (error instanceof ApiError) {
            return sendErrorResponse(res, error);
        }

        if (error?.message?.includes("already exists")) {
            return sendErrorResponse(res, Errors.webhookAlreadyExists(req.body?.url), 409);
        }

        if (error?.message?.includes("Tenant")) {
            return sendErrorResponse(res, Errors.tenantNotFound(req.body?.tenant_id), 404);
        }

        return sendErrorResponse(
            res,
            Errors.internalError(error?.message ?? "Failed to create webhook"),
            500
        );
    }
}
