import { Request, Response } from 'express';
import { TenantApiServices } from '../services/TenantApiServices';
import {
  sendErrorResponse,
  sendSuccessResponse,
  ApiError,
} from '../../../utils/errorHandler';
import type { AuthenticatedRequest } from '../middlewares/auth';
import { ErrorCode } from '../../../utils/APIContract';

export async function createWebhook(req: Request, res: Response) {
  try {
    const { url, events } = req.body as {
      url?: string;
      events?: string[];
    };

    if (!url) {
      return sendErrorResponse(
        res,
        new ApiError(
          ErrorCode.MISSING_REQUIRED_FIELD,
          'Missing required field: url',
          400,
          'url'
        )
      );
    }

    const authReq = req as AuthenticatedRequest;
    const tenantId = authReq.tenant?.id;

    if (!tenantId) {
      return sendErrorResponse(
        res,
        new ApiError(ErrorCode.AUTH_REQUIRED, 'Authentication required', 401)
      );
    }

    const tenantApiServices = new TenantApiServices();
    const webhook = await tenantApiServices.createWebhook({
      tenant_id: tenantId,
      url,
      events: events || [],
      secret: '', // Generated by service
    });

    return sendSuccessResponse(res, 201, 'Webhook created successfully', {
      id: webhook.id,
      tenant_id: webhook.tenant_id,
      url: webhook.url,
      events: webhook.events,
      created_at: webhook.created_at,
      updated_at: webhook.updated_at,
    });
  } catch (error: any) {
    if (error instanceof ApiError) {
      return sendErrorResponse(res, error);
    }

    if (error?.message?.includes('already exists')) {
      return sendErrorResponse(
        res,
        new ApiError(
          ErrorCode.WEBHOOK_ALREADY_EXISTS,
          `Webhook for URL '${req.body?.url}' already exists`,
          409,
          'url'
        )
      );
    }

    if (error?.message?.includes('Tenant')) {
      return sendErrorResponse(
        res,
        new ApiError(
          ErrorCode.TENANT_NOT_FOUND,
          `Tenant with ID ${req.body?.tenant?.id || 'undefined'} not found`,
          404
        )
      );
    }

    return sendErrorResponse(
      res,
      new ApiError(
        ErrorCode.INTERNAL_ERROR,
        error?.message ?? 'Failed to create webhook',
        500
      )
    );
  }
}
